typedef struct {
char *question;
char *options[4];
char answer;
int difficulty;
} QuizQuestion;

QuizQuestion quiz[200] = {
{"Welche Zahl entspricht der Kreiszahl Pi?", {"a) 3,14", "b) 3,142", "c) 3,1415", "d) 3,14159"}, 'd', 1},
{"Wer gewann den Nobelpreis für Chemie im Jahr 1964 für seine Arbeit an der Röntgenstrukturanalyse von Kristallen?",{"a) Ernest Rutherford", "b) Dorothy Crowfoot Hodgkin", "c) Linus Pauling", "d) Rosalind Franklin"}, 'b', 2},
{"Wie viel wiegt ein durchschnittlicher Apfel?", {"a) 18g", "b) 25g", "c) 30g", "d) 40g"}, 'c', 1},
{"Was ist die Ordnungszahl von Eisen?", {"a) 55", "b) 62", "c) 26", "d) 30"}, 'c', 2},
{"Welcher Planet ist der näheste zur Sonne?", {"a) Merkur", "b) Venus", "c) Mars", "d) Jupiter"}, 'a', 1},
{"Wer schrieb den Roman 'Die Verwandlung'?", {"a) Franz Kafka", "b) Fjodor Dostojewski", "c) Thomas Mann", "d) George Orwell"}, 'a', 2},
{"Was ist der Unterschied zwischen Amphibien und Reptilien?", {"a) Amphibien haben feuchte Haut und Reptilien haben Schuppen.", "b) Amphibien haben eine trockene Haut und Reptilien haben Schuppen.", "c) Amphibien haben Schuppen und Reptilien haben eine trockene Haut.", "d) Amphibien und Reptilien unterscheiden sich nicht in ihrer äußeren Beschaffenheit."},'a', 2},
{"Welche der folgenden Sprachen ist die am meisten gesprochene in China?", {"a) Kantonisch", "b) Mandarin", "c) Shanghaier Dialekt", "d) Fukuanesisch"}, 'b', 1},
{"Wie viele Atome sind in einem Mol?", {"a) 6,022 * 10^23", "b) 1,04 * 10^23", "c) 2,01 * 10^24", "d) 4,023 * 10^23"}, 'a', 3},
{"Wer malte das Gemälde 'Der Nachtmahr'?", {"a) Francisco de Goya", "b) Caspar David Friedrich", "c) Johann Heinrich Füssli", "d) Vincent Van Gogh"}, 'c', 3},
{"Wer war der erste Mensch, der einen Fuß auf den Mond setzte?", {"a) Buzz Aldrin", "b) Neil Armstrong", "c) Michael Collins", "d) Yuri Gagarin"}, 'b', 1},
{"Wie viele Elemente sind in der modernen Version des Periodensystems enthalten?", {"a) 118", "b) 101", "c) 90", "d) 136"}, 'a', 2},
{"Wer war Autor des Buches 1984?", {"a) George Orwell", "b) Aldous Huxley", "c) Joseph Conrad", "d) Ernest Hemingway"}, 'a', 1},
{"Welches ist das größte Land der Erde?", {"a) Russland", "b) China", "c) USA", "d) Kanada"}, 'a', 1},
{"Was bezeichnet das Wort 'amphibisch'?", {"a) Ein Tier, das sowohl im Wasser als auch an Land lebt.", "b) Ein Tier, das nur an Land lebt.", "c) Ein Flugzeug, das auf dem Wasser starten und landen kann.", "d) Ein feuchtigkeitsbeständiges Material."}, 'a', 2},
{"Welches ist der größte Kontinent?", {"a) Afrika", "b) Asien", "c) Nordamerika", "d) Europa"}, 'b', 1},
{"Wer entdeckte den Elektron?", {"a) Francis Crick", "b) Albert Einstein", "c) J.J. Thomson", "d) Max Planck"}, 'c', 3},
{"Welches ist das kleinste Land der Welt?", {"a) Vatikanstadt", "b) Monaco", "c) San Marino", "d) Nauru"}, 'a', 1},
{"In welchem Jahr wurde die Berliner Mauer abgerissen?", {"a) 1989", "b) 1990", "c) 1991", "d) 1992"}, 'a', 1},
{"Wer war der führende Komponist der Wiener Klassik?", {"a) Wolfgang Amadeus Mozart", "b) Ludwig van Beethoven", "c) Franz Schubert", "d) Johann Strauss II"}, 'a', 3},
{"Wie oft wurde Margaret Thatcher zur Premierministerin von Großbritannien gewählt?", {"a) 2", "b) 3", "c) 4", "d) 5"}, 'b', 2},
{"Welches ist das kleinste Teilchen eines chemischen Elements?", {"a) Molekül", "b) Atom", "c) Isotop", "d) Proton"}, 'b', 2},
{"Wer war der erste Präsident der USA?", {"a) George Washington", "b) Thomas Jefferson", "c) Abraham Lincoln", "d) John F. Kennedy"}, 'a', 1},
{"Welches Land hat die meisten Zeitzone?", {"a) USA", "b) Kanada", "c) Russland", "d) China"}, 'c', 3},
{"Was ist die chemische Formel für Wasser?", {"a) CO2", "b) NaCl", "c) H2O", "d) CH4"}, 'c', 1},
{"Wer war der Autor des Buches 'Faust'?", {"a) Johann Wolfgang von Goethe", "b) Friedrich Schiller", "c) Heinrich Heine", "d) Thomas Mann"}, 'a', 2},
{"Was ist der meistverkaufte Roman aller Zeiten?", {"a) 'Harry Potter und der Stein der Weisen' von J.K. Rowling", "b) 'Der Herr der Ringe' von J.R.R. Tolkien", "c) 'Die Bibel'", "d) 'Don Quijote' von Miguel de Cervantes"}, 'c', 2},
{"Wer war der Gründer von Microsoft?", {"a) Bill Gates", "b) Jeff Bezos", "c) Steve Jobs", "d) Mark Zuckerberg"}, 'a', 1},
{"Welches ist das am meisten produzierte Getreide der Welt?", {"a) Reis", "b) Weizen", "c) Mais", "d) Hirse"}, 'c', 1},
{"Wer war der erste Mensch im Weltraum?", {"a) Neil Armstrong", "b) Buzz Aldrin", "c) Yuri Gagarin", "d) John Glenn"}, 'c', 2},
{"Wie viele Beine hat ein Spinnen?", {"a) 4", "b) 6", "c) 8", "d) 10"}, 'c', 1},
{"Welches Land gilt als der größte Produzent von Kaffee?", {"a) Brasilien", "b) Kolumbien", "c) Vietnam", "d) Äthiopien"}, 'a', 1},
{"Wie heißt das Orgelstück, das bei Hochzeiten oft gespielt wird?", {"a) Toccata d-Moll", "b) Hochzeitsmarsch", "c) Ave Maria", "d) Jetzt kommt die Feuerwehr raus"}, 'b', 1},
{"In welchem Jahr ereignete sich die Französische Revolution?", {"a) 1689", "b) 1789", "c) 1889", "d) 1989"}, 'b', 2},
{"Welches ist das längste Flusssystem der Welt?", {"a) Nil", "b) Amazonas", "c) Yangtse", "d) Mississippi"}, 'b', 2},
{"Wer schrieb das Buch 'Die Schatzinsel'?", {"a) Jules Verne", "b) Lewis Carroll", "c) Robert Louis Stevenson", "d) Mark Twain"}, 'c', 2},
{"Welches ist das höchste Bauwerk der Welt?", {"a) Empire State Building", "b) Taipei 101", "c) Burj Khalifa", "d) Tokyo Skytree"}, 'c', 2},
{"In welcher Stadt befindet sich das weltberühmte Opernhaus 'La Scala'?", {"a) Paris", "b) Wien", "c) New York", "d) Mailand"}, 'd', 2},
{"Welche Sprache ist die offizielle Sprache von Brasilien?", {"a) Spanisch", "b) Portugiesisch", "c) Englisch", "d) Französisch"}, 'b', 1},
{"Welches Land hat die meisten Einwohner?", {"a) Japan", "b) Russland", "c) China", "d) Indien"}, 'd', 1},
{"Wer entdeckte das Penicillin?", {"a) Alexander Fleming", "b) Louis Pasteur", "c) Robert Koch", "d) Jonas Salk"}, 'a', 3},
{"Wie heißt der längste Fluss Europas?", {"a) Donau", "b) Wolga", "c) Rhein", "d) Dnepr"}, 'b', 2},
{"Welcher Planet ist der zweitgrößte im Sonnensystem?", {"a) Mars", "b) Jupiter", "c) Saturn", "d) Venus"}, 'c', 2},
{"Wer hat das Telefon erfunden?", {"a) Alexander Bell", "b) Thomas Edison", "c) Guglielmo Marconi", "d) Samuel Morse"}, 'a', 2},
{"Wie werden Tiere genannt, die sowohl Pflanzen als auch Fleisch fressen?", {"a) Veganer", "b) Herbivoren", "c) Omnivoren", "d) Carnivoren"}, 'c', 1},
{"Wie heißt die höchste Erhebung der Erde?", {"a) Mount Everest", "b) Kilimandscharo", "c) Mount McKinley", "d) Mont Blanc"}, 'a', 2},
{"Welcher Planet ist bekannt als 'der rote Planet'?", {"a) Merkur", "b) Mars", "c) Venus", "d) Pluto"}, 'b', 1},
{"Welches sind die drei Primärfarben?", {"a) Rot, Blau, Grün", "b) Orange, Lila, Braun", "c) Gelb, Schwarz, Weiß", "d) Pink, Türkis, Gold"}, 'a', 1},
{"Wer erhielt 1908 als erster Mensch den Nobelpreis für Chemie?", {"a) Marie Curie", "b) Albert Einstein", "c) Johannes Diderik van der Waals", "d) Bertha von Suttner"}, 'a', 3},
{"Welches ist das einzige Land in der Welt, das auf vier Kontinenten liegt?", {"a) Russland", "b) Türkei", "c) Saudi-Arabien", "d) Kasachstan"}, 'b', 3},
{"Wer schrieb das Buch 'Robinson Crusoe'?", {"a) Daniel Defoe", "b) Charles Dickens", "c) Edgar Allan Poe", "d) Jane Austen"}, 'a', 2},
{"Wann fiel die Berliner Mauer?", {"a) 1985", "b) 1987", "c) 1989", "d) 1991"}, 'c', 1},
{"Welcher Fluss fließt durch \"Washington D.C.\"?", {"a) Mississippi", "b) Hudson", "c) Potomac", "d) Colorado"}, 'c', 2},
{"Wer war der Gründer von Apple Inc.?", {"a) Steve Jobs", "b) Jeff Bezos", "c) Bill Gates", "d) Mark Zuckerberg"}, 'a', 1},
{"Welches Land grenzt an Uruguay?", {"a) Peru", "b) Chile", "c) Brasilien", "d) Argentinien"}, 'd', 2},
{"Wie viele Tage dauert ein Jahr auf der Venus?", {"a) 45", "b) 146", "c) 243", "d) 365"}, 'c', 3},
{"Wie heißt der erste Satellit der Erde, der 1957 ins All geschickt wurde?", {"a) Explorer 1", "b) Sputnik 1", "c) Apollo 11", "d) Vanguard 1"}, 'b', 2},
{"In welchem Land liegt Mount Fuji?", {"a) Japan", "b) China", "c) Nepal", "d) Südkorea"}, 'a', 1},
{"Wie heißt das kleinste Land der Europäischen Union?", {"a) Malta", "b) Zypern", "c) Estland", "d) Luxemburg"}, 'a', 2},
{"Wer war der erste Kaiser Roms?", {"a) Augustus Caesar", "b) Julius Caesar", "c) Caligula", "d) Nero"}, 'a', 2},
{"In welchem Jahr ereignete sich der 11. September?", {"a) 2000", "b) 2001", "c) 2002", "d) 2003"}, 'b', 1},
{"Welches ist das größte Tier der Welt?", {"a) Blauwal", "b) Elefant", "c) Nashorn", "d) Giraffe"}, 'a', 1},
{"Welches ist das größte Riff der Welt?", {"a) Tintenfisch-Riff", "b) Großes Barriereriff", "c) Rotes Riff", "d) Azoren-Riff"}, 'b', 2},
{"Wer war der erste Mensch, der einen Fuß auf den Mond setzte?", {"a) Buzz Aldrin", "b) Neil Armstrong", "c) Michael Collins", "d) Yuri Gagarin"}, 'b', 1},
{"Wie viele Elemente sind in der modernen Version des Periodensystems enthalten?", {"a) 118", "b) 101", "c) 90", "d) 136"}, 'a', 2},
{"Wer war Autor des Buches 1984?", {"a) George Orwell", "b) Aldous Huxley", "c) Joseph Conrad", "d) Ernest Hemingway"}, 'a', 1},
{"Welches ist das größte Land der Erde?", {"a) Russland", "b) China", "c) USA", "d) Kanada"}, 'a', 1},
{"Was bezeichnet das Wort 'amphibisch'?", {"a) Ein Tier, das sowohl im Wasser als auch an Land lebt.", "b) Ein Tier, das nur an Land lebt.", "c) Ein Flugzeug, das auf dem Wasser starten und landen kann.", "d) Ein feuchtigkeitsbeständiges Material."}, 'a', 2},
{"Welches ist der größte Kontinent?", {"a) Afrika", "b) Asien", "c) Nordamerika", "d) Europa"}, 'b', 1},
{"Wer entdeckte den Elektron?", {"a) Francis Crick", "b) Albert Einstein", "c) J.J. Thomson", "d) Max Planck"}, 'c', 3},
{"Welches ist das kleinste Land der Welt?", {"a) Vatikanstadt", "b) Monaco", "c) San Marino", "d) Nauru"}, 'a', 1},
{"In welchem Jahr wurde die Berliner Mauer abgerissen?", {"a) 1989", "b) 1990", "c) 1991", "d) 1992"}, 'a', 1},
{"Wer war der führende Komponist der Wiener Klassik?", {"a) Wolfgang Amadeus Mozart", "b) Ludwig van Beethoven", "c) Franz Schubert", "d) Johann Strauss II"}, 'a', 3},
{"Wie oft wurde Margaret Thatcher zur Premierministerin von Großbritannien gewählt?", {"a) 2", "b) 3", "c) 4", "d) 5"}, 'b', 2},
{"Welches ist das Kleinste Teilchen eines chemischen Elements?", {"a) Molekül", "b) Atom", "c) Isotop", "d) Proton"}, 'b', 2},
{"Wer war der erste Präsident der USA?", {"a) George Washington", "b) Thomas Jefferson", "c) Abraham Lincoln", "d) John F. Kennedy"}, 'a', 1},
{"Welches Land hat die meisten Zeitzone?", {"a) USA", "b) Kanada", "c) Russland", "d) China"}, 'c', 3},
{"Was ist die chemische Formel für Wasser?", {"a) CO2", "b) NaCl", "c) H2O", "d) CH4"}, 'c', 1},
{"Wer war der Autor des Buches 'Faust'?", {"a) Johann Wolfgang von Goethe", "b) Friedrich Schiller", "c) Heinrich Heine", "d) Thomas Mann"}, 'a', 2},
{"Was ist der meistverkaufte Roman aller Zeiten?", {"a) 'Harry Potter und der Stein der Weisen' von J.K. Rowling", "b) 'Der Herr der Ringe' von J.R.R. Tolkien", "c) 'Die Bibel'", "d) 'Don Quijote' von Miguel de Cervantes"}, 'c', 2},
{"Wer war der Gründer von Microsoft?", {"a) Bill Gates", "b) Jeff Bezos", "c) Steve Jobs", "d) Mark Zuckerberg"}, 'a', 1},
{"Welches ist das am meisten produzierte Getreide der Welt?", {"a) Reis", "b) Weizen", "c) Mais", "d) Hirse"}, 'c', 1},
{"Wer war der erste Mensch im Weltraum?", {"a) Neil Armstrong", "b) Buzz Aldrin", "c) Yuri Gagarin", "d) John Glenn"}, 'c', 2},
{"Wie viele Beine hat eine Spinne?", {"a) 4", "b) 6", "c) 8", "d) 10"}, 'c', 1},
{"Welches Land gilt als der größte Produzent von Kaffee?", {"a) Brasilien", "b) Kolumbien", "c) Vietnam", "d) Äthiopien"}, 'a', 1},
{"Wie heißt das Orgelstück, das bei Hochzeiten oft gespielt wird?", {"a) Toccata d-Moll", "b) Hochzeitsmarsch", "c) Ave Maria", "d) Jetzt kommt die Feuerwehr raus"}, 'b', 1},
{"In welchem Jahr ereignete sich die Französische Revolution?", {"a) 1689", "b) 1789", "c) 1889", "d) 1989"}, 'b', 2},
{"Welches ist das längste Flusssystem der Welt?", {"a) Nil", "b) Amazonas", "c) Yangtse", "d) Mississippi"}, 'b', 2},
{"Wer schrieb das Buch 'Die Schatzinsel'?", {"a) Jules Verne", "b) Lewis Carroll", "c) Robert Louis Stevenson", "d) Mark Twain"}, 'c', 2},
{"Welches ist das höchste Bauwerk der Welt?", {"a) Burj Khalifa", "b) Shanghai Tower", "c) Abraj Al Bait Clock Tower", "d) Ping An Finance Center"}, 'a', 1},
{"Welche Farbe haben die Blätter im Herbst?", {"a) Grün", "b) Gelb", "c) Orange", "d) Rot"}, 'd', 1},
{"In welchem Jahr wurde die Magna Carta unterzeichnet?", {"a) 1215", "b) 1315", "c) 1415", "d) 1515"}, 'a', 2},
{"Wer war der erste Mensch, der den Nordpol erreichte?", {"a) Roald Amundsen", "b) Robert Peary", "c) Edmund Hillary", "d) Neil Armstrong"}, 'b', 3},
{"Welches ist das tiefste Gewässer der Welt?", {"a) Marianengraben", "b) Puerto Rico-Graben", "c) Tongagraben", "d) Kurilengraben"}, 'a', 1},
{"Wer war der Gründer von Apple?", {"a) Bill Gates", "b) Jeff Bezos", "c) Steve Jobs", "d) Mark Zuckerberg"}, 'c', 1},
{"Welches ist das größte Lebewesen der Welt?", {"a) Elefant", "b) Wal", "c) Bär", "d) Giraffe"}, 'b', 2},
{"Welches Land hat die meisten Einwohner?", {"a) Russland", "b) USA", "c) Indien", "d) China"}, 'd', 1},
{"Welches ist das höchste Gebirge der Welt?", {"a) Anden", "b) Rocky Mountains", "c) Himalaya", "d) Alpen"}, 'c', 1},
{"Wie heißt die Hauptstadt von Australien?", {"a) Sydney", "b) Perth", "c) Melbourne", "d) Canberra"}, 'd', 1},
{"Wie heißt die kleinste Insel der Welt?", {"a) Aitutaki", "b) Nauru", "c) Palau", "d) Pitcairn"}, 'd', 2},
{"Wer malte die Mona Lisa?", {"a) Vincent van Gogh", "b) Leonardo da Vinci", "c) Pablo Picasso", "d) Michelangelo"}, 'b', 1},
{"Welches ist das schnellste Landtier?", {"a) Gepard", "b) Antilope", "c) Pferd", "d) Löwe"}, 'a', 1},
{"Wie viele Zeitzonen gibt es auf der Welt?", {"a) 20", "b) 24", "c) 30", "d) 35"}, 'b', 2},
{"Wer schrieb die Tragödie 'Romeo und Julia'?", {"a) William Shakespeare", "b) Friedrich Schiller", "c) Johann Wolfgang von Goethe", "d) Dante Alighieri"}, 'a', 1},
{"Welches ist das meistgesprochene Sprache der Welt?", {"a) Englisch", "b) Chinesisch", "c) Spanisch", "d) Hindi"}, 'b', 1},
{"Wer war der erste Mensch, der die Antarktis erreichte?", {"a) Roald Amundsen", "b) Robert Scott", "c) Ernest Shackleton", "d) Richard Byrd"}, 'b', 3},
{"Welches Land hat den größten Waffenexport?", {"a) USA", "b) Russland", "c) China", "d) Deutschland"}, 'd', 1},
{"In welchem Jahr wurde die erste Pizza in Italien gebacken?", {"a) 1700", "b) 1780", "c) 1830", "d) 1889"}, 'd', 2},
{"Welches ist das am schwersten zugängliche Gebiet der Erde?", {"a) Wüste Sahara", "b) Dschungel Amazonas", "c) Antarktis", "d) Gobi-Wüste"}, 'c', 1},
{"Wie viele Musiker spielen normalerweise in einem Streichquartett?", {"a) 2", "b) 3", "c) 4", "d) 5"}, 'c', 1},
{"Welches ist das am häufigsten gezüchtete Nutztier der Welt?", {"a) Rind", "b) Huhn", "c) Schwein", "d) Schaf"}, 'b', 1},
{"Wie viele Sterne hat die amerikanische Flagge?", {"a) 45", "b) 50", "c) 55", "d) 60"}, 'b', 1},
{"Wer war der erste Mensch, der den Mount Everest bestieg?", {"a) Sir Edmund Hillary", "b) Tenzing Norgay", "c) Reinhold Messner", "d) George Mallory"}, 'a', 2},
{"Welches ist das größte Meer der Welt?", {"a) Pazifik", "b) Atlantik", "c) Indischer Ozean", "d) Südlicher Ozean"}, 'a', 1},
{"Welches Land hat die älteste Nationalflagge?", {"a) Großbritannien", "b) Dänemark", "c) Frankreich", "d) Japan"}, 'b', 2},
{"Wer war der erste Kanzler der Bundesrepublik Deutschland?", {"a) Willy Brandt", "b) Helmut Schmidt", "c) Konrad Adenauer", "d) Gerhard Schröder"}, 'c', 1},
{"Welches ist das meistverkaufte Automodell der Welt?", {"a) VW Käfer", "b) Toyota Corolla", "c) Honda Civic", "d) Ford Mustang"}, 'b', 1},
{"In welchem Jahr wurde der erste Computer erfunden?", {"a) 1939", "b) 1944", "c) 1951", "d) 1960"}, 'a', 2},
{"Welches ist das kleinste Säugetier der Welt?", {"a) Spitzmaus", "b) Fledermaus", "c) Mäuse", "d) Ratte"}, 'b', 1},
{"Wie viele Bundesstaaten hat die USA?", {"a) 48", "b) 49", "c) 50", "d) 51"}, 'c', 1},
{"Welches ist das am meisten besuchte Land der Welt?", {"a) USA", "b) Spanien", "c) Frankreich", "d) China"}, 'c', 1},
{"Wer war der erste Bundespräsident der Bundesrepublik Deutschland?", {"a) Richard von Weizsäcker", "b) Heinrich Lübke", "c) Theodor Heuss", "d) Gustav Heinemann"}, 'c', 1},
{"Welches ist das größte Land in Europa?", {"a) Deutschland", "b) Frankreich", "c) Spanien", "d) Russland"}, 'd', 1},
{"Wer schrieb die Novelle 'Der Schimmelreiter'?", {"a) Theodor Fontane", "b) Thomas Mann", "c) Franz Kafka", "d) Hermann Hesse"}, 'a', 2},
{"Welches ist das giftigste Tier der Welt?", {"a) Krokodil", "b) Löwe", "c) Blauer Pfeilgiftfrosch", "d) Schwarze Mamba"}, 'd', 1},
{"In welchem Jahr wurde die erste Postkarte verschickt?", {"a) 1860", "b) 1870", "c) 1880", "d) 1890"}, 'a', 2},
{"Wer schrieb den Roman 'Die Verwandlung'?", {"a) Franz Kafka", "b) Dostojewski", "c) Hemingway", "d) Thomas Mann"}, 'a', 1},
{"Welches ist das bekannteste Gemälde von Leonardo da Vinci?", {"a) Der letzte Abendmahl", "b) Die Geburt der Venus", "c) Die Mona Lisa", "d) Das Mädchen mit dem Perlenohrring"}, 'c', 1},
{"Wie heißt der höchste Berg in Deutschland?", {"a) Watzmann", "b) Zugspitze", "c) Hoher Dachstein", "d) Großglockner"}, 'b', 1},
{"Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?", {"a) Willy Brandt", "b) Helmut Schmidt", "c) Konrad Adenauer", "d) Gerhard Schröder"}, 'c', 1},
{"Wie heißt der Fluss, der durch Paris fließt?", {"a) Themse", "b) Rhein", "c) Seine", "d) Loire"}, 'c', 1},
{"Wer schrieb die Trilogie 'Herr der Ringe'?", {"a) J.K. Rowling", "b) J.R.R. Tolkien", "c) C.S. Lewis", "d) George R.R. Martin"}, 'b', 1},
{"Welches ist das am meisten besuchte Museum der Welt?", {"a) Louvre", "b) British Museum", "c) National Museum of China", "d) Metropolitan Museum of Art"}, 'a', 1},
{"Wer war der erste Mensch, der einen Fuß auf den Mond setzte?", {"a) Buzz Aldrin", "b) Neil Armstrong", "c) Michael Collins", "d) Yuri Gagarin"}, 'b', 1},
{"Welches ist das längste Fluss-System der Welt?", {"a) Nil", "b) Mississippi", "c) Amazonas", "d) Yangtze"}, 'c', 1},
{"Wer hat das erste iPhone erfunden?", {"a) Steve Jobs", "b) Bill Gates", "c) Tim Cook", "d) Mark Zuckerberg"}, 'a', 1},
{"Welches ist das höchste Gebäude der Welt?", {"a) Burj Khalifa", "b) Shanghai Tower", "c) Abraj Al Bait Clock", "d) Ping An Finance Center"}, 'a', 1},
{"Wer war der erste Präsident der USA?", {"a) Thomas Jefferson", "b) George Washington", "c) John Adams", "d) Abraham Lincoln"}, 'b', 1},
{"In welchem Jahr fand die erste Mondlandung statt?", {"a) 1969", "b) 1972", "c) 1967", "d) 1971"}, 'a', 1},
{"Wer hat das erste Flugzeug erfunden?", {"a) Orville Wright", "b) Wilbur Wright", "c) Leonardo da Vinci", "d) Samuel Langley"}, 'a', 1},
{"Wie viele Menschen leben in Japan?", {"a) etwa 100 Millionen", "b) etwa 50 Millionen", "c) etwa 10 Millionen", "d) etwa 200 Millionen"}, 'a', 1},
{"Wie heißt die längste Schlange der Welt?", {"a) Anakonda", "b) Königskobra", "c) Python", "d) Boa"}, 'c', 1},
{"Wie viele Knochen hat der menschliche Körper?", {"a) 206", "b) 300", "c) 150", "d) 100"}, 'a', 1},
{"Wie heißt die Währung von Japan?", {"a) Yen", "b) Yuan", "c) Won", "d) Rubel"}, 'a', 1},
{"Wie lang ist der Äquator?", {"a) etwa 20.000 km", "b) etwa 40.000 km", "c) etwa 10.000 km", "d) etwa 60.000 km"}, 'b', 1},
{"Wie viele Elemente hat das Periodensystem?", {"a) 118", "b) 100", "c) 92", "d) 150"}, 'a', 1},
{"Wie heißt das höchste Gebirge der Welt?", {"a) Anden", "b) Rocky Mountains", "c) Himalaya", "d) Alpen"}, 'c', 1},
{"Wer ist der Gründer von Amazon?", {"a) Steve Jobs", "b) Tim Cook", "c) Jeff Bezos", "d) Bill Gates"}, 'c', 1},
{"Auf welchem Kontinent liegt Brasilien?", {"a) Afrika", "b) Asien", "c) Europa", "d) Südamerika"}, 'd', 1},
{"Wie heißt die Hauptstadt von Spanien?", {"a) Barcelona", "b) Valencia", "c) Sevilla", "d) Madrid"}, 'd', 1},
{"Wer hat die Relativitätstheorie entwickelt?", {"a) Isaac Newton", "b) Albert Einstein", "c) Galileo Galilei", "d) Stephen Hawking"}, 'b', 1},
{"Wie heißt der größte Ozean der Welt?", {"a) Atlantik", "b) Indischer Ozean", "c) Pazifik", "d) Arktischer Ozean"}, 'c', 1},
{"Wie heißt der längste Fluss Europas?", {"a) Donau", "b) Rhein", "c) Wolga", "d) Dnepr"}, 'a', 1},
{"Wie viele Bundesstaaten hat die USA?", {"a) 50", "b) 48", "c) 52", "d) 46"}, 'a', 1},
{"Wie viele Sterne hat die amerikanische Flagge?", {"a) 50", "b) 48", "c) 52", "d) 46"}, 'a', 1},
{"Wie lautet der Familienname des Physikers Werner?", {"a) Heisenberg", "b) Schrödinger", "c) Planck", "d) Einstein"}, 'a', 1},
{"Wie heißt der höchste Berg Europas?", {"a) Mont Blanc", "b) Matterhorn", "c) Elbrus", "d) Mount Everest"}, 'c', 1},
{"Welches ist das kleinste Land der Welt?", {"a) Monaco", "b) Vatikanstadt", "c) San Marino", "d) Liechtenstein"}, 'b', 1},
{"Wer war der erste Mensch, der die Schwerelosigkeit erlebt hat?", {"a) Neil Armstrong", "b) Yuri Gagarin", "c) John Glenn", "d) Alan Shepard"}, 'b', 1},
{"Was ist das härteste Mineral auf der Mohs-Skala?", {"a) Diamant", "b) Quarz", "c) Topas", "d) Korund"}, 'a', 1},
{"Wie viele Zähne hat ein erwachsener Mensch normalerweise?", {"a) 32", "b) 28", "c) 36", "d) 24"}, 'a', 1},
{"Wer schrieb das Buch 'Harry Potter'?", {"a) Suzanne Collins", "b) J.K. Rowling", "c) Stephenie Meyer", "d) Veronica Roth"}, 'b', 1},
{"Wer erfand das Telephon?", {"a) Alexander Graham Bell", "b) Thomas Edison", "c) Nicola Tesla", "d) Albert Einstein"}, 'a', 1},
{"Welches ist das größte Land der Erde?", {"a) Russland", "b) Kanada", "c) China", "d) USA"}, 'a', 1},
{"Welches ist das schwerste Element?", {"a) Blei", "b) Gold", "c) Uran", "d) Platin"}, 'c', 1},
{"Wer entdeckte Amerika?", {"a) Christoph Kolumbus", "b) Ferdinand Magellan", "c) Vasco da Gama", "d) Amerigo Vespucci"}, 'a', 1},
{"Wie heißt der Erfinder der Glühbirne?", {"a) Thomas Edison", "b) Nikola Tesla", "c) Benjamin Franklin", "d) George Washington Carver"}, 'a', 1},
{"Welches Gas wird in Glühlampen verwendet?", {"a) Quecksilberdampf", "b) Stickstoffdioxid", "c) Sauerstoff", "d) Kohlenstoffdioxid"}, 'd', 1},
{"Wie heißt die Hauptstadt von Russland?", {"a) Sankt Petersburg", "b) Moskau", "c) Kiew", "d) Minsk"}, 'b', 1},
{"Wie heißt das Gebirge, das sich entlang der Ostküste Australiens erstreckt?", {"a) Rocky Mountains", "b) Himalaya", "c) Anden", "d) Great Dividing Range"}, 'd', 1},
{"Wie nennt man das Ungeheuer, das angeblich im Loch Ness lebt?", {"a) Bigfoot", "b) Yeti", "c) Sasquatch", "d) Nessie"}, 'd', 1},
{"Welcher Planet ist der sechste des Sonnensystems?", {"a) Saturn", "b) Jupiter", "c) Uranus", "d) Neptun"}, 'a', 1},
{"Wie heißt der längste Fluss der USA?", {"a) Potomac", "b) Colorado", "c) Missouri", "d) Mississippi"}, 'd', 1},
{"Wie heißt der höchste Berg der USA?", {"a) Denali", "b) Mount Rainier", "c) Mount Whitney", "d) Longs Peak"}, 'a', 1},
{"Was ist das schnellste Landtier der Welt?", {"a) Leopard", "b) Gepard", "c) Löwe", "d) Tiger"}, 'b', 1},
{"Wofür ist Johann Sebastian Bach berühmt?", {"a) Oper", "b) Ballett", "c) Chorwerke", "d) Jazzmusik"}, 'c', 1},
{"Wie lautet die chemische Formel für Wasser?", {"a) CO2", "b) NaCl", "c) H2O", "d) O2"}, 'c', 1},
{"Wie viele Millimeter sind in einem Zentimeter?", {"a) 10", "b) 100", "c) 1000", "d) 10000"}, 'a', 1},
{"Wie viele Sekunden hat eine Minute?", {"a) 60", "b) 100", "c) 10", "d) 1000"}, 'a', 1},
{"Wie heißt die Hauptstadt von Australien?", {"a) Sydney", "b) Canberra", "c) Melbourne", "d) Brisbane"}, 'b', 1},
{"Wie viele Bundesländer hat Deutschland?", {"a) 16", "b) 10", "c) 12", "d) 8"}, 'a', 1},
{"Wie heißt die Hauptstadt von Kanada?", {"a) Vancouver", "b) Toronto", "c) Ottawa", "d) Montreal"}, 'c', 1},
{"Wie heißt das Original von Michelangelos berühmter Skulptur 'David'?", {"a) David", "b) Jupiter", "c) Apollo", "d) Merkur"}, 'a', 1},
{"Wie heißt der höchste Berg Nordamerikas?", {"a) Mount Logan", "b) Denali", "c) Mount Everest", "d) Aconcagua"}, 'b', 1},
{"Wer komponierte die 'Eine kleine Nachtmusik'?", {"a) Wolfgang Amadeus Mozart", "b) Ludwig van Beethoven", "c) Franz Schubert", "d) Johann Sebastian Bach"}, 'a', 1},
{"Welches ist das teuerste Edelstein?", {"a) Smaragd", "b) Rubin", "c) Saphir", "d) Diamant"}, 'd', 1},
{"Wie wird das Jahr 2022 auf römisch geschrieben?", {"a) MMXXI", "b) MMXXIII", "c) MMXXII", "d) MMIIXX"}, 'c', 1},
{"Wer hat das Gesetz der Schwerkraft entdeckt?", {"a) Isaac Newton", "b) Albert Einstein", "c) Galileo Galilei", "d) Stephen Hawking"}, 'a', 1},
{"Wie heißen die größten Seen der USA?", {"a) Großer Salzsee und Totes Meer", "b) Michigansee und Totes Meer", "c) Lake Tahoe und Totes Meer", "d) Oberer See und Michigansee"}, 'd', 1},
{"Wer hat die Mona Lisa gemalt?", {"a) Leonardo da Vinci", "b) Vincent van Gogh", "c) Rembrandt van Rijn", "d) Michelangelo Buonarroti"}, 'a', 1},
{"Welches ist das längste Wort der deutschen Sprache?", {"a) Donaudampfschiffahrtskapitän", "b) Audiokassettenaufnahmegerät", "c) Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz", "d) Floccinaucinihilipilifikation"}, 'c', 1},
{"Wie heißt der Fluss, der durch Paris fließt?", {"a) Seine", "b) Themse", "c) Donau", "d) Rhein"}, 'a', 1},
{"Wie heißt das höchste Gebäude Europas?", {"a) The Shard", "b) Eiffelturm", "c) Commerzbank Tower", "d) Lakhta Center"}, 'd', 1},
{"In welchem Jahr wurde die Berliner Mauer errichtet?", {"a) 1961", "b) 1952", "c) 1965", "d) 1970"}, 'a', 1},
{"Wie heißt der größte See der Welt nach Hause?", {"a) Arktischer Ozean", "b) Kaspisches Meer", "c) Victoria-See", "d) Lake Superior"}, 'b', 1},
{"Wie nennt man den längsten zusammenhängenden Gebirgszug der Erde?", {"a) Rocky Mountains", "b) Anden", "c) Himalaya", "d) Alpen"}, 'c', 1},
{"Welches ist das kleinste Land Europas?", {"a) Malta", "b) Andorra", "c) Monaco", "d) Liechtenstein"}, 'c', 1},
{"In welchem Land liegt der Eiffelturm?", {"a) England", "b) Deutschland", "c) Frankreich", "d) Italien"}, 'c', 1},
{"Welcher Schauspieler spielt die Hauptrolle in der 'Matrix' Trilogie?", {"a) Tom Hanks", "b) Brad Pitt", "c) Johnny Depp", "d) Keanu Reeves"}, 'd', 1},
{"Wer war der erste Mensch im Weltall?", {"a) Buzz Aldrin", "b) Neil Armstrong", "c) Michael Collins", "d) Yuri Gagarin"}, 'd', 1},
{"Wer malte die Sixtinische Kapelle im Vatikan?", {"a) Michelangelo Buonarroti", "b) Leonardo da Vinci", "c) Raffael", "d) Sandro Botticelli"}, 'a', 1},
{"Wie viele Liter Blut hat ein erwachsener Mensch?", {"a) etwa 10 Liter", "b) etwa 5 Liter", "c) etwa 20 Liter", "d) etwa 15 Liter"}, 'b', 1},
{"Welches ist das kleinste Bundesland Deutschlands?", {"a) Bayern", "b) Saarland", "c) Bremen", "d) Hessen"}, 'c', 1},
{"Wie viele Sterne hat die EU-Flagge?", {"a) 12", "b) 10", "c) 8", "d) 14"}, 'a', 1},
{"Welches ist das längste Tier der Welt?", {"a) Blauwal", "b) Riesenkalmar", "c) Walhai", "d) Krokodil"}, 'b', 1},
{"In welchem Jahr fiel die Berliner Mauer?", {"a) 1989", "b) 1991", "c) 1987", "d) 1993"}, 'a', 1},
{"Wie viele Kammern hat das menschliche Herz?", {"a) 4", "b) 2", "c) 6", "d) 8"}, 'a', 1},
{"Wie viele Kontinente gibt es auf der Welt?", {"a) 7", "b) 6", "c) 5", "d) 4"}, 'a', 1},
{"Wie heißt der höchste Berg Südamerikas?", {"a) Aconcagua", "b) Ojos del Salado", "c) Chimborazo", "d) Popocatépetl"}, 'a', 1},
{"Wie heißt die höchste Brücke der Welt?", {"a) Si Du River Bridge", "b) Akashi-Kaikyō Bridge", "c) Duge Bridge", "d) Yavuz Sultan Selim Bridge"}, 'c', 1},
{"Wie lautet die chemische Formel für Kohlenstoff?", {"a) CO", "b) CO2", "c) H2O", "d) N2"}, 'b', 1},
{"Wer schrieb das Buch 'Die Verwandlung'?", {"a) Fjodor Dostojewski", "b) Franz Kafka", "c) Thomas Mann", "d) Hermann Hesse"}, 'b', 1},
{"Wie heißt die Hauptstadt von Brasilien?", {"a) São Paulo", "b) Brasília", "c) Rio de Janeiro", "d) Salvador"}, 'b', 1},
{"Wer hat das Mikroskop erfunden?", {"a) Galileo Galilei", "b) Robert Hooke", "c) Robert Boyle", "d) Antoni van Leeuwenhoek"}, 'd', 1},
{"Wie heißt der höchste Berg Australiens?", {"a) Mount Cook", "b) Mount Kosciuszko", "c) Puncak Jaya", "d) Mount Wilhelm"}, 'b', 1},
{"Welches ist das kleinste der 4 Elemente?", {"a) Luft", "b) Wasser", "c) Erde", "d) Feuer"}, 'a', 1},
{"Wer hat den Computer erfunden?", {"a) Bill Gates", "b) Alan Turing", "c) Tim Cook", "d) Steve Jobs"}, 'b', 1},
{"Wie heißt der Fluss, der durch Ägypten fließt?", {"a) Nil", "b) Mississippi", "c) Amazonas", "d) Yangtze"}, 'a', 1},
{"Wie viele Menschen leben derzeit auf der Erde?", {"a) etwa 7,9 Milliarden", "
